# Generated by Django 4.0.1 on 2022-01-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='rate',
            new_name='isbad',
        ),
    ]
