# Generated by Django 4.0.1 on 2022-01-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='section',
            field=models.CharField(choices=[('BL', 'BLUSAS'), ('SV', 'SAYAS /VESTIDOS'), ('RI', 'ROPA INTERIOR'), ('PL', 'Pantalones/Licras'), ('CP', 'CAMISAS/ PULOVERES '), ('PH', 'PANTALONES DE HOMBRE'), ('MI', 'MIXTOS')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
