# Generated by Django 4.0.1 on 2022-01-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_client_description_remove_client_isbad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reasons',
        ),
    ]
