# Generated by Django 4.0.1 on 2022-01-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_section_delete_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='order',
            name='extra_price',
            field=models.FloatField(default=0),
        ),
    ]
