# Generated by Django 4.0.1 on 2022-01-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_reasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderservice',
            name='extra_price',
        ),
        migrations.AddField(
            model_name='order',
            name='extra_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
