# Generated by Django 4.0.1 on 2022-01-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_orderservice_extra_price_order_extra_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
    ]
