# Generated by Django 4.0.1 on 2022-01-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_options_alter_order_extra_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task', models.TextField(max_length=400)),
                ('stamptime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
