# Generated by Django 2.2.24 on 2021-12-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtelierWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
