# Generated by Django 2.2.24 on 2021-12-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AtelierWebApp', '0002_auto_20211226_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AtelierWebApp.Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AtelierWebApp.Servicio'),
        ),
    ]
