# Generated by Django 2.2.24 on 2021-12-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtelierWebApp', '0003_auto_20211228_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
