# Generated by Django 2.2.24 on 2021-12-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AtelierWebApp', '0004_auto_20211228_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='price',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='seccion',
        ),
        migrations.AddField(
            model_name='servicio',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AtelierWebApp.seccion_genero'),
        ),
        migrations.AlterField(
            model_name='seccion_genero',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AtelierWebApp.Seccion'),
        ),
    ]
