# Generated by Django 2.2.24 on 2021-12-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AtelierWebApp', '0005_pedido_servicio2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='servicio3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio3', to='AtelierWebApp.Servicio'),
        ),
    ]
